import { ICommand } from "../ex[2-4]/Core/Command";
import { StrategyCraftAutoGeneratedClassStr } from "./StrategyCraftAutoGeneratedClassStr";
import { StrategyGenerateAdapters } from "./StrategyGenerateAdapters";

export const createStrategyGenerateAdapters = (): ICommand =>
  new StrategyGenerateAdapters(new StrategyCraftAutoGeneratedClassStr());
